version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: ks-mysql
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
#    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    container_name: ks-redis
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - "6379:6379"
#    restart: always

  nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: ks-nacos
    ports:
      - "8848:8848"
#    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_PARAM=allowPublicKeyRetrieval=true
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: ks-rabbitmq
#    restart: always
    volumes:
      - mq-data:/var/lib/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql-data:
  redis-data:
  mq-data:
